# Creates the git-ignored .env used by docker compose, with fresh random secrets.
# Existing .env files are never overwritten.
#
#   powershell -ExecutionPolicy Bypass -File .\docker\init-env.ps1

$root = Split-Path $PSScriptRoot -Parent
$target = Join-Path $root '.env'
if (Test-Path $target) {
    Write-Host ".env already exists - left unchanged."
    exit 0
}

$alphabet = [char[]]'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789'
$rng = [Security.Cryptography.RandomNumberGenerator]::Create()
function New-Secret([int]$length) {
    $bytes = New-Object byte[] $length
    $rng.GetBytes($bytes)
    -join ($bytes | ForEach-Object { $alphabet[$_ % $alphabet.Length] })
}

$content = @"
# docker compose settings. Generated by docker/init-env.ps1. Never commit this file.
FRONTEND_PORT=8080

DB_NAME=credit_card_payment_db
DB_USER=ccps_app
DB_PASSWORD=$(New-Secret 32)
MYSQL_ROOT_PASSWORD=$(New-Secret 32)

DJANGO_SECRET_KEY=$(New-Secret 60)
JWT_SECRET_KEY=$(New-Secret 64)

# First-run admin account (created once if missing). Change the password after logging in.
DJANGO_SUPERUSER_USERNAME=admin
DJANGO_SUPERUSER_EMAIL=admin@localhost
DJANGO_SUPERUSER_PASSWORD=$(New-Secret 20)

ENABLE_API_DOCS=True
"@
[IO.File]::WriteAllText($target, $content.Replace("`r`n", "`n"))
Write-Host "Created $target with random secrets."
Write-Host "The first-run admin password is in that file (DJANGO_SUPERUSER_PASSWORD)."
