# Generated by Django 5.2.17 on 2026-09-29 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('login', 'Admin login'), ('login_failed', 'Failed admin login'), ('logout', 'Admin logout'), ('user_created', 'User created'), ('user_updated', 'User updated'), ('user_password_changed', 'User password changed'), ('user_deleted', 'User deleted'), ('card_list_viewed', 'Card list viewed'), ('card_viewed', 'Card viewed'), ('card_deleted', 'Card deleted'), ('transaction_list_viewed', 'Transaction list viewed'), ('transaction_viewed', 'Transaction viewed'), ('transactions_exported', 'Transactions exported (CSV)'), ('daily_summary_viewed', 'Daily summary viewed'), ('object_created', 'Object created'), ('object_updated', 'Object updated'), ('object_deleted', 'Object deleted')], db_index=True, max_length=40)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='Admin who performed the action. Null for failed logins or deleted admins.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'admin log',
                'verbose_name_plural': 'admin logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='adminlog_user_created_idx')],
            },
        ),
    ]
