# Generated by Django 5.2.17 on 2026-09-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('login', 'Admin login'), ('login_failed', 'Failed admin login'), ('logout', 'Admin logout'), ('user_list_viewed', 'User list viewed'), ('user_created', 'User created'), ('user_updated', 'User updated'), ('user_password_changed', 'User password changed'), ('user_deleted', 'User deleted'), ('card_list_viewed', 'Card list viewed'), ('card_viewed', 'Card viewed'), ('card_deleted', 'Card deleted'), ('transaction_list_viewed', 'Transaction list viewed'), ('transaction_viewed', 'Transaction viewed'), ('transactions_exported', 'Transactions exported (CSV)'), ('daily_summary_viewed', 'Daily summary viewed'), ('admin_logs_viewed', 'Admin logs viewed'), ('object_created', 'Object created'), ('object_updated', 'Object updated'), ('object_deleted', 'Object deleted')], db_index=True, max_length=40),
        ),
    ]
