# Creates database/dumps/credit_card_payment_system.sql from the local MySQL database.
#
#   powershell -ExecutionPolicy Bypass -File .\database\create_dump.ps1
#
# The dump holds the complete schema plus the reference data Django needs to
# recognise it (applied migrations, content types, permissions). It holds NO
# accounts, password hashes, sessions, refresh tokens, audit logs, cards or
# payments, so it can be shared without exposing credentials or customer data.
# Connection settings are read from backend/django_backend/.env (never printed).

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$outDir = Join-Path $PSScriptRoot 'dumps'
$target = Join-Path $outDir 'credit_card_payment_system.sql'
$tmp = Join-Path $env:TEMP "ccps_dump_$([guid]::NewGuid().ToString('N'))"
New-Item -ItemType Directory -Force $outDir, $tmp | Out-Null

$cfg = @{}
foreach ($line in Get-Content "$root\backend\django_backend\.env") { if ($line -match '^([A-Z_]+)=(.*)$') { $cfg[$Matches[1]] = $Matches[2] } }
$db = $cfg['DB_NAME']
$common = @('-h', $cfg['DB_HOST'], '-P', $cfg['DB_PORT'], '-u', $cfg['DB_USER'],
            '--single-transaction', '--no-tablespaces', '--set-gtid-purged=OFF', '--skip-dump-date',
            '--default-character-set=utf8mb4', '--skip-comments')
$referenceTables = @('django_migrations', 'django_content_type', 'auth_permission')

try {
    $env:MYSQL_PWD = $cfg['DB_PASSWORD']
    & mysqldump @common --no-data --result-file="$tmp\schema.sql" $db
    if ($LASTEXITCODE) { throw 'mysqldump (schema) failed' }
    & mysqldump @common --no-create-info --skip-triggers --order-by-primary --complete-insert `
        --result-file="$tmp\data.sql" $db @referenceTables
    if ($LASTEXITCODE) { throw 'mysqldump (reference data) failed' }
    $server = (& mysql -h $cfg['DB_HOST'] -P $cfg['DB_PORT'] -u $cfg['DB_USER'] -N -e 'SELECT VERSION()')
} finally {
    $env:MYSQL_PWD = $null
}

$utf8 = New-Object System.Text.UTF8Encoding($false)
$schema = [IO.File]::ReadAllText("$tmp\schema.sql", $utf8)
$data = [IO.File]::ReadAllText("$tmp\data.sql", $utf8)
# Start every table's id counter from 1 in a fresh database (no hint of past rows).
$schema = [regex]::Replace($schema, ' AUTO_INCREMENT=\d+', '')

$header = @"
-- =============================================================================
-- Credit Card Payment System - MySQL database dump
-- Source: MySQL $server, database '$db'. Generated by database/create_dump.ps1.
--
-- Contents
--   * Complete schema: all tables, indexes, foreign keys and CHECK constraints.
--   * Reference data Django needs to recognise the schema:
--       django_migrations, django_content_type, auth_permission.
--   * NO user accounts or password hashes, sessions, refresh tokens, audit
--     logs, cards or payments. Card tables never contain full card numbers or
--     CVVs by design (masked number and last 4 digits only).
--
-- Import into an empty database (utf8mb4):
--   CREATE DATABASE credit_card_payment_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
--   mysql -u <user> -p credit_card_payment_db < credit_card_payment_system.sql
-- Then, from backend/django_backend:
--   python manage.py migrate            (reports nothing to apply)
--   python manage.py createsuperuser    (create your own admin account)
-- =============================================================================

"@
$body = $header + $schema.TrimEnd() + "`n`n-- Reference data`n" + $data.TrimEnd() + "`n"
[IO.File]::WriteAllText($target, $body.Replace("`r`n", "`n"), $utf8)
Remove-Item -LiteralPath $tmp -Recurse -Force

$info = Get-Item $target
Write-Host "Wrote $($info.FullName) ($([math]::Round($info.Length / 1KB, 1)) KB)"
