"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Secrets and environment-specific values come from .env (git-ignored).
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]

# Extra origins allowed to POST forms (the Django admin) when behind a proxy.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

# Number of trusted reverse proxies in front of Django (nginx in docker compose).
# 0 = X-Forwarded-For is client-controlled and ignored; the TCP peer is the client.
# N = the client is the address the Nth proxy saw (N-th entry from the right).
# Used for rate limiting, the admin lockout and audit-log IPs.
NUM_PROXIES = int(os.getenv('DJANGO_NUM_PROXIES', '0'))


def _env_flag(name, default):
    return os.getenv(name, str(default)).lower() == 'true'


# Production hardening (DEBUG=False): HTTPS only, secure cookies, HSTS.
# DJANGO_SECURE_SSL_REDIRECT=False is only for testing production mode over
# plain HTTP locally. Behind a TLS-terminating proxy set
# DJANGO_SECURE_PROXY_SSL_HEADER=True so Django recognises HTTPS requests.
if not DEBUG:
    SECURE_SSL_REDIRECT = _env_flag('DJANGO_SECURE_SSL_REDIRECT', True)
    SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # Opt-in: only once the domain is ready for the browsers' HSTS preload list.
    SECURE_HSTS_PRELOAD = _env_flag('DJANGO_SECURE_HSTS_PRELOAD', False)
    # Secure (HTTPS-only) cookies. DJANGO_SECURE_COOKIES=False is only for running
    # the production build over plain HTTP on localhost (e.g. docker compose).
    SESSION_COOKIE_SECURE = _env_flag('DJANGO_SECURE_COOKIES', True)
    CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE
    if _env_flag('DJANGO_SECURE_PROXY_SSL_HEADER', False):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    # Local
    'accounts',
    'cards',
    'payments',
    'adminlogs',
    'adminpanel',
]

MIDDLEWARE = [
    'config.middleware.RealClientIPMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static files (Django admin, Swagger UI) without a separate web server.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Must come before CommonMiddleware so CORS headers are added to all responses.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.ApiNoStoreMiddleware',
]

# CORS: only the listed frontend origins may call the API from a browser.
# The API uses Bearer tokens, not cookies, so credentials are not allowed.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('DJANGO_CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]
CORS_URLS_REGEX = r'^/api/.*$'
# Needed so the browser sends the httpOnly refresh cookie to /api/auth/.
# Safe because origins are an explicit allow-list, never '*'.
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # filled by `collectstatic` (done in the Docker image)
# In development serve straight from the apps, so collectstatic is not needed locally.
WHITENOISE_USE_FINDERS = DEBUG


# Cache (login throttles, admin lockout). The default in-memory cache is per
# process; DJANGO_CACHE_BACKEND=database shares it between all server workers
# (run `manage.py createcachetable` once).

if os.getenv('DJANGO_CACHE_BACKEND', 'locmem') == 'database':
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.db.DatabaseCache', 'LOCATION': 'django_cache'}}


# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Django REST Framework

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # JSON only. The browsable API re-renders submitted form data on
    # validation errors, which would echo card numbers back into HTML.
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Brute-force protection for the public auth endpoints (per client IP).
    # Must match the trusted proxy count, otherwise DRF identifies clients by the
    # client-supplied X-Forwarded-For header and rate limits can be bypassed.
    'NUM_PROXIES': NUM_PROXIES,
    'DEFAULT_THROTTLE_RATES': {
        'login': os.getenv('THROTTLE_LOGIN_RATE', '10/min'),
        'register': os.getenv('THROTTLE_REGISTER_RATE', '10/hour'),
    },
}


# JWT (djangorestframework-simplejwt)

SIMPLE_JWT = {
    'SIGNING_KEY': os.environ['JWT_SECRET_KEY'],
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ACCESS_TOKEN_LIFETIME': timedelta(seconds=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME_SECONDS', '300'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(seconds=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME_SECONDS', '86400'))),
    # Each refresh issues a new refresh token and blacklists the old one.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# The refresh token lives in an httpOnly cookie that page JavaScript cannot
# read; the short-lived access token is kept in the frontend's memory only.
AUTH_REFRESH_COOKIE = {
    'key': 'ccps_refresh',
    'path': '/api/auth/',
    'httponly': True,
    'samesite': 'Strict',
    # HTTPS-only outside local development.
    'secure': os.getenv('AUTH_COOKIE_SECURE', str(not DEBUG)).lower() == 'true',
}


# API documentation (drf-spectacular): /api/schema/, /api/docs/ (Swagger UI), /api/redoc/.
# On for development; set ENABLE_API_DOCS=False in production.

ENABLE_API_DOCS = _env_flag('ENABLE_API_DOCS', True)

SPECTACULAR_SETTINGS = {
    'TITLE': 'Credit Card Payment System - Django API',
    'VERSION': '1.0.0',
    'DESCRIPTION': (BASE_DIR / 'config' / 'api_description.md').read_text(encoding='utf-8'),
    'SERVE_INCLUDE_SCHEMA': False,
    # Separate request/response components so write-only fields (card_number,
    # password) never appear in response schemas.
    'COMPONENT_SPLIT_REQUEST': True,
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'SERVE_AUTHENTICATION': [],
    'TAGS': [
        {'name': 'Authentication', 'description': 'Register, log in, refresh, log out.'},
        {'name': 'Cards', 'description': 'Saved cards. Stored and returned masked only.'},
        {'name': 'Transactions', 'description': "The signed-in user's payment history."},
        {'name': 'Admin', 'description': 'Staff only. Each section needs the matching Django view permission.'},
    ],
    'SWAGGER_UI_SETTINGS': {'persistAuthorization': False, 'displayRequestDuration': True},
    'ENUM_NAME_OVERRIDES': {
        'CardTypeEnum': 'cards.models.Card.CardType',
        'PaymentStatusEnum': 'payments.models.Payment.Status',
    },
}
