# Generated by Django 5.2.17 on 2026-09-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'transaction', 'verbose_name_plural': 'transactions'},
        ),
    ]
